"""Engine-neutral scientific dependency and compatibility planning."""

from .analysis_registry import AnalysisRegistry, RegistryError
from .compatibility import SemanticPlanner, compatibility_fingerprint, node_result_from_inputs
from .experiment_graph import (
    EXPERIMENT_NODE_IDS,
    EXPERIMENT_STAGES,
    EXPERIMENT_TARGETS,
    ExperimentExecutionResult,
    build_experiment_plan,
    execute_experiment_target,
    experiment_node_specs,
    experiment_stage_result_metadata,
    format_experiment_plan,
    plan_experiment,
    resolve_experiment_target,
)
from .semantic_graph import (
    AnalysisScope,
    ArtifactIdentity,
    ArtifactRecord,
    ArtifactValidation,
    ChannelDependency,
    ChannelFingerprint,
    ChannelSpec,
    CompatibilityFingerprint,
    DependencyResultIdentity,
    NodeInputs,
    NodeResult,
    PlanDecision,
    PlanState,
    SemanticNodeSpec,
    SemanticPlan,
)

__all__ = [
    "AnalysisRegistry",
    "AnalysisScope",
    "ArtifactIdentity",
    "ArtifactRecord",
    "ArtifactValidation",
    "ChannelDependency",
    "ChannelFingerprint",
    "ChannelSpec",
    "CompatibilityFingerprint",
    "DependencyResultIdentity",
    "EXPERIMENT_NODE_IDS",
    "EXPERIMENT_STAGES",
    "EXPERIMENT_TARGETS",
    "ExperimentExecutionResult",
    "NodeInputs",
    "NodeResult",
    "PlanDecision",
    "PlanState",
    "RegistryError",
    "SemanticNodeSpec",
    "SemanticPlan",
    "SemanticPlanner",
    "build_experiment_plan",
    "compatibility_fingerprint",
    "execute_experiment_target",
    "experiment_node_specs",
    "experiment_stage_result_metadata",
    "format_experiment_plan",
    "node_result_from_inputs",
    "plan_experiment",
    "resolve_experiment_target",
]
