# Deaminase footprinting defaults
extends: default
conversion_types: 
  - '5mC' # 5mC

mod_target_bases:
- "C"

# Duplicate Detection Params
duplicate_detection_site_types:
  - "any_C"

# Autocorrelation params
autocorr_site_types:
  - "any_C"

# Correlation matrix params
correlation_matrix_site_types:
  - "any_C_site"