# Generic defaults
bam_suffix: ".bam"
split_dir: "demultiplexed_BAMs"
strands:
  - bottom
  - top
conversions:
  - unconverted
mapping_threshold: 0.01 # Minimum proportion of mapped reads that need to fall within a region to include in the final AnnData.
model: "hac" # needed for dorado basecaller
threads: 4
aligner: "minimap2" # Aligner to use: dorado, minimap2
aligner_args:
  minimap2:
    - '-a'
    - '-x'
    - 'map-ont'
    - '--MD'
    - '-Y' 
    - '-y'
    - '-N'
    - '5'
    - '--secondary=no' 
  dorado:
    - "--mm2-opts"
    - "-N"
    - "5"
device: "auto"
mod_target_bases:
  - "GpC"
  - "CpG"
enzyme_target_bases:
  - "GpC"
filter_threshold: 0.8
barcode_both_ends: False # dorado demultiplexing
trim: False # dorado adapter and barcode removal during demultiplexing
input_already_demuxed: False # If the input files are already demultiplexed.
make_bigwigs: False # Whether to make coverage bigwigs
sample_sheet_path: null